Fixes issue with `txData` reference
GridPlus/eth-lattice-keyring pull request #54
Opened 2022-09-16 22:13 UTC by douglance

I believe this issue is from [this PR](https://github.com/GridPlus/eth-lattice-keyring/pull/37/files). It looks like it was referring to an object that was removed. 

I think we are supposed to check if the transaction is a type that we can't handle (anything other than `0`) so I changed the check to refer to `tx._type`

2022-09-16 22:21 UTC, alex-miller-0 approved these changes
good catch

2022-09-16 23:15 UTC, alex-miller-0 requested changes
@douglance can you bump fix version for this pls

2022-09-17 14:48 UTC, douglance commented
Removed boolean check entirely and bumped to `0.12.2`

2022-09-17 19:38 UTC, alex-miller-0 approved these changes

2022-09-18 12:50 UTC, merged